export const FETCH_LIST_ITEM_REQUEST = 'FETCH_LIST_ITEM_REQUEST';
export const FETCH_LIST_ITEM_SUCCESS = 'FETCH_LIST_ITEM_SUCCESS';
export const FETCH_LIST_ITEM_FAILURE = 'FETCH_LIST_ITEM_FAILURE';

export const FETCH_ITEM_REQUEST = 'FETCH_ITEM_REQUEST';
export const FETCH_ITEM_SUCCESS = 'FETCH_ITEM_SUCCESS';
export const FETCH_ITEM_FAILURE = 'FETCH_ITEM_FAILURE';
